### ISSUE TITLE
suggested post-new hook doesn't handle spaces in file names

### ISSUE THREAD

**Issue by gauteh** [guyzmo/notmuch-abook#22]
the hook
```
# first update notmuch-abook
for file in $(notmuch search --output=files tag:new) ; do
  cat $file | $HOME/.bin/notmuch-abook update
done
```

doesn't handle messages in folders with spaces, it is probably sufficient to wrap `$file` in quotes.

**Comment by gauteh** [comment]
I'm pretty sure this is the problem, I have not experienced any problems after wrapping $file in qutoes:

```sh
for file in $(notmuch search --output=files tag:new) ; do
  cat "$file" | "$HOME"/.bin/notmuch-abook update
done
```

It should be safer to use quotes anyway.

**Comment by gauteh** [comment]
In fact this still gives me issues; I have to do it this way:

```shell
oi=$IFS
IFS=$(echo -en "\n\b") # allow spaces in file name
for file in $(notmuch search --output=files tag:new) ; do
  cat "$file" | $HOME/.bin/notmuch-abook update
done
IFS=$oi
```

**Comment by guyzmo** [comment]
ok, hopefully now that there is a `notmuch address` command, that part won't be necessary anymore, as I'll drop the sqlite database.
