### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by ff2000** [guyzmo/notmuch-abook#28]
```
$ python3 ~/bin/notmuch-abook
  File "/home/franz/bin/notmuch-abook", line 387
    print "added %d addresses" % n
                             ^
SyntaxError: invalid syntax
```
I changed the first line to `#!/usr/bin/env python2` which fixes the error in case the default python interpreter is set to python3. But supporting python3 would be even better. I am not a python guy, but if you don't have the time I could try to get it running at least.

**Comment by guyzmo** [comment]
ah! good catch, I try to make all my python code py3 ready, and missed that one. The only issue is that vim can be compiled without py3 support and make that plugin not working fine. And I'm not sure the `__future__` module can be imported…

**Comment by guyzmo** [comment]
done, all code should be py2 _and_ py3 ready

**Comment by ff2000** [comment]
Now I get 
```
$ notmuch-abook -v lookup Karl
Traceback (most recent call last):
  File "/home/franz/bin/notmuch-abook", line 471, in run
    lookup_action(db, options['<match>'], options['--format'])
  File "/home/franz/bin/notmuch-abook", line 409, in lookup_action
    print_address_list(db.lookup(match), output_format)
  File "/home/franz/bin/notmuch-abook", line 363, in print_address_list
    out.write(output + '\n')
TypeError: can't concat bytes to str
```

**Comment by guyzmo** [comment]
fixed ;-)

**Comment by ff2000** [comment]
On Mon, 24 Aug 2015 10:47:00 -0700, guyzmo <notifications@github.com> wrote:
> fixed ;-)

In fact :) Thx!
