### ISSUE TITLE
quoting of names with spaces

### ISSUE THREAD

**Issue by gauteh** [guyzmo/notmuch-abook#33]
Should not the name part (when containing spaces) be quoted? E.g:

`"A B" <asdf@asdf.as>`

**Comment by guyzmo** [comment]
nope, it shall not. Except if there's a comma within it: 

`"Bar, Foo" <foo.bar@example.org>` vs `Foo Bar <foo.bar@example.org>`.

**Comment by gauteh** [comment]
guyzmo writes on March 10, 2016 16:29:
> nope, it shall not. Except if there's a comma within it: 
> 
> `"Bar, Foo" <foo.bar@example.org>` vs `Foo Bar <foo.bar@example.org>`.

Ok, thanks.
