### ISSUE TITLE
Plugin not initializing

### ISSUE THREAD

**Issue by pedrohc** [guyzmo/notmuch-abook#34]
Getting the following error when opening vim to edit a notmuch-compose mail.

"~/.cache/astroid/1462908842-astroid-4-0t0e70cswt-21261@lunar" 5L, 65C
Erro detectado ao processar function InitAddressBook:
linha    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NotMuchConfig'
linha    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfg' is not defined

Repo cloned in ~/.vim/bundle/notmuch_abook/, plugin copied to autoload dir, and loaded with pathogen.
lib instaled via 'python setup.py install
OS: Arch Linux

**Comment by guyzmo** [comment]
ok, so on the good side, the plugin is indeed loading ☺

…but your vim's python is not finding the `notmuch_abook` module. What it usually means is that the python you've compiled your vim with is not the same python you've used to install `notmuch_abook` (even though in theory vim should be able to load the module from the `pythonx` directory).

To test this, try on your command line to run:

```
% python
>>> from notmuch_abook import notmuch_abook
>>> notmuch_abook.NotMuchConfig
```

and within vim

```
:py from notmuch_abook import notmuch_abook
:py notmuch_abook.NotMuchConfig
```

you should get no attribute error on the command line, but likely to get one from within vim.

**Comment by pedrohc** [comment]
Yes, I think you're right.
After uninstalling the system notmuch_abook package, vim loaded the class from pythonix without problems.

Guess I'll have to use this one, instead of installing it.

Thanks.

**Comment by guyzmo** [comment]
Good to know that it's working, but it'd be nice to try to understand _why_ it's misbehaving… Did you run both tests as I suggested in my former comment? What did it return? I'm wondering whether the `setup.py` installation is broken…

**Comment by pedrohc** [comment]
I did both tests, and it returned nothing. The error ocurred while loading the plugin, when opening a mail file inside astroid mail client. It uses an embedded gvim. 

The setup.py was the only method that worked actually, for installation. pip2 did not work, it claimed that it didn't find the notmuch_abook.py file. And pip3 complained about unsuported pysqlite in python 3.

Maybe it has something to do with Arch Linux. Python 3 is the default in Arch, and I had problems in the past because of this, with other plugins. My vim is compiled with support for both python versions though.

**Comment by guyzmo** [comment]
Well, you might have issues with your arch's python, but sadly things are slightly broken as well for installing the tool. I anyway intend on getting rid of the sqlite3 db to rely on notmuch's address results, which will need a good rewrite of the tool. Then I'll try to improve distribution as well ☺
